"""Per-user resume format store (XML) plus the protected application default."""

from __future__ import annotations

from resume_writer.formats.adapter import get_format_for_writer
from resume_writer.formats.extract import add_format_from_docx, extract_format_from_docx
from resume_writer.formats.models import (
    CANONICAL_SECTION_KEYS,
    DEFAULT_FORMAT_ID,
    DEFAULT_FORMAT_NAME,
    DEFAULT_FORMAT_VALUES,
    FORMAT_XML_VERSION,
    DocumentStructure,
    ExperienceLayout,
    FormatError,
    FormatNotFoundError,
    FormatProtectedError,
    FormatValidationError,
    HeadingStyle,
    PageBorderStyle,
    ResumeFormatSpec,
    SectionRule,
    SeparatorStyle,
    canonicalize_section_key,
    default_document_structure,
    default_format_spec,
    normalize_line_spacing,
)
from resume_writer.formats.store import (
    create_format,
    default_format_xml,
    delete_format,
    format_spec_from_xml,
    format_spec_to_xml,
    format_template_path,
    get_format,
    get_primary_format,
    list_formats,
    resolve_format_template_path,
    set_primary_format,
    update_format,
)

__all__ = [
    "CANONICAL_SECTION_KEYS",
    "DEFAULT_FORMAT_ID",
    "DEFAULT_FORMAT_NAME",
    "DEFAULT_FORMAT_VALUES",
    "FORMAT_XML_VERSION",
    "DocumentStructure",
    "ExperienceLayout",
    "FormatError",
    "FormatNotFoundError",
    "FormatProtectedError",
    "FormatValidationError",
    "HeadingStyle",
    "PageBorderStyle",
    "ResumeFormatSpec",
    "SectionRule",
    "SeparatorStyle",
    "add_format_from_docx",
    "canonicalize_section_key",
    "create_format",
    "default_document_structure",
    "default_format_spec",
    "default_format_xml",
    "delete_format",
    "extract_format_from_docx",
    "format_spec_from_xml",
    "format_spec_to_xml",
    "format_template_path",
    "get_format",
    "get_format_for_writer",
    "get_primary_format",
    "list_formats",
    "normalize_line_spacing",
    "resolve_format_template_path",
    "set_primary_format",
    "update_format",
]
